name: new_dart_excersice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:  
  intl: ^0.17.0  # Use the latest version available
  
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
